version: '3.6'

services:
  restserver:
    build: .
    image: restserver
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - "postgres"
    command: /opt/jboss/wildfly/bin/standalone.sh -bmanagement=0.0.0.0 -b 0.0.0.0
  postgres:
    image: postgres:12.0
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=patientdb
    logging:
        options:
          max-size: 10m
          max-file: "3"
    volumes:
      - ./src/main/resources/ddl/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 5432:5432